# Generated by Django 3.0.8 on 2020-07-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20200726_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appusers',
            name='profil_url',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
    ]
