# Generated by Django 3.0.8 on 2020-07-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20200727_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusers',
            name='is_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appusers',
            name='profil_url',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
